name: 'version-net'
author: 'Dominik Sysojew-Osinski'
description: 'Automatic version bumper for dotnet CI/CD pipeline'
branding:
  icon: bookmark
  color: blue
inputs:
  dotnet_project_files:
    description: 'list of csproj files which should be bumped up. '
    required: false
    default: '**/*.csproj'
runs:
  using: 'node16'
  main: 'dist/index.js'