name: 'version-net'
author: 'Dominik Sysojew-Osinski'
description: 'Automatic version bumper for dotnet CI/CD pipeline'
inputs:
  dotnet_project_files:
    description: 'list of csproj files which should be bumped up. '
    required: false
    default: '**/*.csproj'
  git_create_tag:
    description: 'should repository be tagged with the version'
    required: false
    default: true
runs:
  using: 'node16'
  main: 'dist/index.js'